### ISSUE TITLE
缓存播放

### ISSUE THREAD

**Issue by superzhangbao** [lipangit/JiaoZiVideoPlayer#2496]
**需求描述
1.我看说明中demo加入了缓存播放的事例，但是没有找到在哪个文件，还请作者告知
2.我目前使用的是6.4.3版本，要想使用缓存功能，是否需要升级？
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
参考第三方videocache项目，提供播放缓存的文件路径

**Comment by superzhangbao** [comment]
谢谢，已经实现缓存效果

**Comment by dongfangmingjia** [comment]
请问，这个怎么实现的

**Comment by superzhangbao** [comment]
> 请问，这个怎么实现的

https://github.com/danikula/AndroidVideoCache 你用这个项目就可以实现缓存了

**Comment by allDreamzq** [comment]
@superzhangbao 请问如何实现的，我这边实现的时候报了
![image](https://user-images.githubusercontent.com/28727860/81471494-0941b300-9224-11ea-8829-98dffb0aa44d.png)

**Comment by allDreamzq** [comment]
com.danikula.videocache.ProxyCacheException: Error closing socket input stream. Version: 2.7.0

**Comment by allDreamzq** [comment]
还请大神指点一下

**Comment by lipangit** [comment]
兄弟去缓存项目里问问



---原始邮件---
发件人: "allDreamzq"<notifications@github.com&gt;
发送时间: 2020年5月9日(周六) 晚上6:37
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 缓存播放 (#2496)




 
还请大神指点一下

**Comment by lucf1103** [comment]
和上面兄弟一样的bug，需要这么解决呀？？
更新了 2.7.1 连续播放一个视频10次+  也会报错：
关键信息：Caused by: com.danikula.videocache.ProxyCacheException: Error using xxx as disc cache. Version: 2.7.1
Caused by: java.io.FileNotFoundException: /storage/xxxxx download: open failed: ENAMETOOLONG (File name too long)

我还试了 直接不用缓存..播放前贼慢，要加载3秒才开始...   求指点

**Comment by lipangit** [comment]
保持关注



---原始邮件---
发件人: "JoyStone"<notifications@github.com&gt;
发送时间: 2020年5月21日(周四) 下午2:44
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 缓存播放 (#2496)




 
和上面兄弟一样的bug，需要这么解决呀？？
 更新了 2.7.1 连续播放一个视频10次+  也会报错：
 关键信息：Caused by: com.danikula.videocache.ProxyCacheException: Error using xxx as disc cache. Version: 2.7.1
 Caused by: java.io.FileNotFoundException: /storage/xxxxx download: open failed: ENAMETOOLONG (File name too long)
 
我还试了 直接不用缓存..播放前贼慢，要加载3秒才开始...   求指点
