### ISSUE TITLE
类似于微信播放视频

### ISSUE THREAD

**Issue by BaiMingxu** [lipangit/JiaoZiVideoPlayer#2635]
您好，大佬们，请问类似于微信朋友圈那种效果怎么实现呀？列表页自动静音播放，点击视频任意位置进入详情页面有声音播放，退出到列表页继续静音自动播放。

**Comment by lipangit** [comment]
继承jzvdStd。  参考demo的smallchangeUiActivity，里面有静音的例子

**Comment by BaiMingxu** [comment]
> 继承jzvdStd。 参考demo的smallchangeUiActivity，里面有静音的例子

大佬里面没有呀？

**Comment by lipangit** [comment]
饺子摇摆是

---原始邮件---
发件人: "BaiMingxu"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 晚上6:51
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635)


 
继承jzvdStd。 参考demo的smallchangeUiActivity，里面有静音的例子
  
大佬里面没有呀？

**Comment by BaiMingxu** [comment]
> 饺子摇摆是
> […](#)
> ---原始邮件--- 发件人: "BaiMingxu"<notifications@github.com&gt; 发送时间: 2020年2月29日(周六) 晚上6:51 收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635) 继承jzvdStd。 参考demo的smallchangeUiActivity，里面有静音的例子 大佬里面没有呀？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬如果用demo那种列表跳详情无缝播放，就会导致JzvdStd.goOnPlayOnPause();和JzvdStd.goOnPlayOnResume();不能使用了。这个怎么解决呀？

**Comment by lipangit** [comment]
视频的标题，下载dwmo查看



---原始邮件---
发件人: "BaiMingxu"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 晚上11:51
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635)


 
饺子摇摆是
 …
 ---原始邮件--- 发件人: "BaiMingxu"<notifications@github.com&gt; 发送时间: 2020年2月29日(周六) 晚上6:51 收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635) 继承jzvdStd。 参考demo的smallchangeUiActivity，里面有静音的例子 大佬里面没有呀？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
大佬如果用demo那种列表跳详情无缝播放，就会导致JzvdStd.goOnPlayOnPause();和JzvdStd.goOnPlayOnResume();不能使用了。这个怎么解决呀？

**Comment by BaiMingxu** [comment]
什么意思？我看ActivityListViewToDetail这里，如果加上JzvdStd.goOnPlayOnPause();JzvdStd.goOnPlayOnResume();那么会有问题

**Comment by lipangit** [comment]
什么问题，描述一下，我给你解决



---原始邮件---
发件人: "BaiMingxu"<notifications@github.com&gt;
发送时间: 2020年3月1日(周日) 晚上9:52
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635)



什么意思？我看ActivityListViewToDetail这里，如果加上JzvdStd.goOnPlayOnPause();JzvdStd.goOnPlayOnResume();那么会有问题

**Comment by BaiMingxu** [comment]
您好，如果加上JzvdStd.goOnPlayOnPause();JzvdStd.goOnPlayOnResume();那么点击进入详情页会抖动。

**Comment by lipangit** [comment]
怎么个抖法



---原始邮件---
发件人: "BaiMingxu"<notifications@github.com&gt;
发送时间: 2020年3月2日(周一) 中午11:08
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635)



您好，如果加上JzvdStd.goOnPlayOnPause();JzvdStd.goOnPlayOnResume();那么点击进入详情页会抖动。

**Comment by BaiMingxu** [comment]
- [
[1583118781163708.mp4.zip](https://github.com/lipangit/JiaoZiVideoPlayer/files/4273253/1583118781163708.mp4.zip)

**Comment by lipangit** [comment]
有时候确实会闪一下，我的是红米note k20，10次闪2次，闪烁时比你录屏的效果要轻微闪烁，和什么有关系呢？我问问&nbsp;https://github.com/Liberations/JiaoZiVideoPlayer&nbsp; 这部分是他做的，他研究的很深入。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BaiMingxu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 中午11:15
收件人:&nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"李盼"<1066666651@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lipangit/JiaoZiVideoPlayer] 类似于微信播放视频 (#2635)



 
[
 1583118781163708.mp4.zip
